import test from "node:test";
import assert from "node:assert/strict";
import { EventEmitter } from "node:events";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { AdultPilotRuntimeSupervisor, resolveAdultPilotRuntimeLaunch } from "../dist-main/main/adult-pilot-runtime-supervisor.js";
const fixture = () => { const base = fs.mkdtempSync(path.join(os.tmpdir(), "mangai-runtime-supervisor-")), root = path.join(base, "runtime", "ComfyUI_windows_portable"), models = path.join(base, "models"); fs.mkdirSync(path.join(root, "python_embeded"), { recursive: true }); fs.mkdirSync(path.join(root, "ComfyUI"), { recursive: true }); fs.mkdirSync(models); fs.writeFileSync(path.join(root, "python_embeded", "python.exe"), "fixture"); fs.writeFileSync(path.join(root, "ComfyUI", "main.py"), "fixture"); fs.writeFileSync(path.join(root, "ComfyUI", "extra_model_paths.yaml"), `# Generated by MANGAI Adult Pilot.\nmangai_adult_pilot:\n  base_path: ${JSON.stringify(fs.realpathSync(models).replaceAll("\\", "/"))}\n`); return { base, root }; };
const childFixture = () => { const child = new EventEmitter(); return Object.assign(child, { pid: 42, killed: false, kill() { this.killed = true; return true; } }); };
test("Adult Pilot launch is fixed to embedded Python and loopback", (t) => { const value = fixture(), root = value.root; t.after(() => fs.rmSync(value.base, { recursive: true, force: true })); const launch = resolveAdultPilotRuntimeLaunch(root); assert.equal(launch.executable, path.join(fs.realpathSync(root), "python_embeded", "python.exe")); assert.deepEqual(launch.args.slice(-5), ["--listen", "127.0.0.1", "--port", "8188", "--disable-auto-launch"]); assert.equal(launch.endpoint, "http://127.0.0.1:8188"); fs.writeFileSync(path.join(root, "ComfyUI", "extra_model_paths.yaml"), "tampered"); assert.throws(() => resolveAdultPilotRuntimeLaunch(root), /検証済み保存領域/); });
test("Adult Pilot supervisor reaches health, prevents duplicate start and stops", async (t) => { const value = fixture(), root = value.root, child = childFixture(), calls = []; let checks = 0; t.after(() => fs.rmSync(value.base, { recursive: true, force: true })); const supervisor = new AdultPilotRuntimeSupervisor({ spawnProcess: (...args) => { calls.push(args); return child; }, checkHealth: async () => ++checks > 1, wait: async () => {} }); assert.equal((await supervisor.start(root)).status, "running"); assert.equal(calls[0][2].shell, false); await assert.rejects(supervisor.start(root), /既に起動/); assert.equal(supervisor.stop().status, "stopped"); assert.equal(child.killed, true); });
test("Adult Pilot supervisor kills an unhealthy runtime", async (t) => { const value = fixture(), root = value.root, child = childFixture(); t.after(() => fs.rmSync(value.base, { recursive: true, force: true })); const supervisor = new AdultPilotRuntimeSupervisor({ spawnProcess: () => child, checkHealth: async () => false, wait: async () => {}, attempts: 2 }); assert.deepEqual(await supervisor.start(root), { status: "failed", message: "ComfyUIの起動確認が時間内に完了しませんでした。" }); assert.equal(child.killed, true); });
test("Adult Pilot supervisor refuses a pre-existing service on its fixed port", async (t) => { const value = fixture(); t.after(() => fs.rmSync(value.base, { recursive: true, force: true })); const supervisor = new AdultPilotRuntimeSupervisor({ spawnProcess: () => { throw new Error("must not spawn"); }, checkHealth: async () => true }); await assert.rejects(supervisor.start(value.root), /別のComfyUI/); });
test("Adult Pilot runtime controls are connected through Main, preload and Wizard", () => {
  const sourceRoot = path.resolve(import.meta.dirname, "..", "src"),
    main = fs.readFileSync(path.join(sourceRoot, "main", "index.ts"), "utf8"),
    preload = fs.readFileSync(path.join(sourceRoot, "preload", "index.ts"), "utf8"),
    wizard = fs.readFileSync(path.join(sourceRoot, "renderer", "features", "ai-settings", "AdultLocalAISetup.tsx"), "utf8");
  for (const route of ["runtime-status", "start-runtime", "stop-runtime"])
    assert.match(main, new RegExp(`ai:adult-pilot:${route}`));
  assert.match(main, /verifyExisting\(v\.root, "checkpoint"\)/);
  assert.match(main, /adultPilotRuntimeSupervisor\.stop\(\)/);
  for (const method of ["adultPilotRuntimeStatus", "startAdultPilotRuntime", "stopAdultPilotRuntime"])
    assert.match(preload, new RegExp(method));
  assert.match(wizard, /settings\.adultSetup\.startRuntime/);
  assert.match(wizard, /settings\.adultSetup\.stopRuntime/);
});
