import fs from "node:fs";
import path from "node:path";
import { spawn, type ChildProcess } from "node:child_process";

export type AdultPilotRuntimeState =
  | { status: "stopped" }
  | { status: "starting"; pid: number | null }
  | { status: "running"; pid: number | null; endpoint: "http://127.0.0.1:8188" }
  | { status: "failed"; message: string };

type RuntimeChild = Pick<ChildProcess, "pid" | "kill" | "once">;
type Dependencies = {
  spawnProcess?: (executable: string, args: readonly string[], options: { cwd: string; windowsHide: true; shell: false; stdio: "ignore" }) => RuntimeChild;
  checkHealth?: () => Promise<boolean>;
  wait?: (milliseconds: number) => Promise<void>;
  attempts?: number;
};
const endpoint = "http://127.0.0.1:8188" as const;

export const resolveAdultPilotRuntimeLaunch = (runtimeRoot: string) => {
  if (!path.isAbsolute(runtimeRoot) || path.parse(runtimeRoot).root.startsWith("\\\\"))
    throw new Error("Runtimeは端末内driveの絶対pathで指定してください。");
  const realRoot = fs.realpathSync(runtimeRoot), executable = path.join(realRoot, "python_embeded", "python.exe"),
    main = path.join(realRoot, "ComfyUI", "main.py"), config = path.join(realRoot, "ComfyUI", "extra_model_paths.yaml");
  if (path.parse(realRoot).root.startsWith("\\\\"))
    throw new Error("Runtimeにnetwork pathは使用できません。");
  for (const [file, label] of [[executable, "embedded Python"], [main, "ComfyUI main.py"], [config, "model path設定"]] as const)
    if (!fs.statSync(file, { throwIfNoEntry: false })?.isFile())
      throw new Error(`${label}を確認できません。Runtimeを再検証してください。`);
  const modelRoot = fs.realpathSync(path.join(realRoot, "..", "..", "models")),
    expectedBasePath = `  base_path: ${JSON.stringify(modelRoot.replaceAll("\\", "/"))}`,
    contents = fs.readFileSync(config, "utf8");
  if (
    path.parse(modelRoot).root.startsWith("\\\\") ||
    !contents.startsWith("# Generated by MANGAI Adult Pilot.") ||
    !contents.split(/\r?\n/).includes(expectedBasePath)
  ) throw new Error("ComfyUI model path設定が検証済み保存領域と一致しません。");
  return { executable, args: ["-s", main, "--windows-standalone-build", "--listen", "127.0.0.1", "--port", "8188", "--disable-auto-launch"] as const, cwd: realRoot, endpoint };
};

export class AdultPilotRuntimeSupervisor {
  private child: RuntimeChild | null = null;
  private state: AdultPilotRuntimeState = { status: "stopped" };
  private readonly spawnProcess;
  private readonly checkHealth;
  private readonly wait;
  private readonly attempts;
  constructor(dependencies: Dependencies = {}) {
    this.spawnProcess = dependencies.spawnProcess ?? ((file, args, options) => spawn(file, [...args], options));
    this.checkHealth = dependencies.checkHealth ?? (async () => {
      try { return (await fetch(`${endpoint}/system_stats`, { signal: AbortSignal.timeout(2_000) })).ok; }
      catch { return false; }
    });
    this.wait = dependencies.wait ?? ((milliseconds) => new Promise((resolve) => setTimeout(resolve, milliseconds)));
    this.attempts = dependencies.attempts ?? 60;
  }
  status() { return this.state; }
  async start(runtimeRoot: string): Promise<AdultPilotRuntimeState> {
    if (this.child || this.state.status === "starting" || this.state.status === "running") throw new Error("Adult Pilot Runtimeは既に起動処理中です。");
    const launch = resolveAdultPilotRuntimeLaunch(runtimeRoot), child = this.spawnProcess(launch.executable, launch.args, { cwd: launch.cwd, windowsHide: true, shell: false, stdio: "ignore" });
    this.child = child;
    this.state = { status: "starting", pid: child.pid ?? null };
    child.once("exit", () => { if (this.child === child) { this.child = null; if (this.state.status !== "failed") this.state = { status: "stopped" }; } });
    child.once("error", () => { if (this.child === child) { this.child = null; this.state = { status: "failed", message: "ComfyUI Runtimeを起動できませんでした。" }; } });
    for (let attempt = 0; attempt < this.attempts; attempt += 1) {
      if (this.child !== child) break;
      if (await this.checkHealth()) return this.state = { status: "running", pid: child.pid ?? null, endpoint };
      await this.wait(500);
    }
    const stoppedEarly = this.status();
    if (stoppedEarly.status === "failed") return stoppedEarly;
    if (this.child === child) { child.kill(); this.child = null; }
    return this.state = { status: "failed", message: "ComfyUIの起動確認が時間内に完了しませんでした。" };
  }
  stop(): AdultPilotRuntimeState {
    const child = this.child; this.child = null; if (child) child.kill();
    return this.state = { status: "stopped" };
  }
}
