import fs from "node:fs";
import path from "node:path";

const requiredRuntimeFiles = [
  ["ComfyUI", "main.py"],
  ["python_embeded", "python.exe"],
  ["run_nvidia_gpu.bat"],
] as const;

const yamlString = (value: string) => JSON.stringify(value.replaceAll("\\", "/"));

export const configureAdultPilotRuntime = (
  extractedRuntimeRoot: string,
  modelRoot: string,
) => {
  if (!path.isAbsolute(extractedRuntimeRoot) || !path.isAbsolute(modelRoot))
    throw new Error("Runtimeとmodel保存先は絶対pathで指定してください。");
  for (const segments of requiredRuntimeFiles) {
    const file = path.join(extractedRuntimeRoot, ...segments);
    if (!fs.statSync(file, { throwIfNoEntry: false })?.isFile())
      throw new Error(`ComfyUI Runtimeの必須fileを確認できません: ${segments.join("/")}`);
  }
  const realModelRoot = fs.realpathSync(modelRoot);
  if (path.parse(realModelRoot).root.startsWith("\\\\"))
    throw new Error("model保存先にnetwork pathは使用できません。");
  for (const directory of ["checkpoints", "vae", "controlnet"]) {
    const target = path.join(realModelRoot, directory);
    if (!fs.statSync(target, { throwIfNoEntry: false })?.isDirectory())
      throw new Error(`検証済みmodel directoryを確認できません: ${directory}`);
  }
  const config = path.join(extractedRuntimeRoot, "ComfyUI", "extra_model_paths.yaml");
  if (fs.existsSync(config))
    throw new Error("既存のComfyUI model path設定は自動上書きしません。");
  const contents = [
    "# Generated by MANGAI Adult Pilot. Do not add cloud or shared-network paths.",
    "mangai_adult_pilot:",
    `  base_path: ${yamlString(realModelRoot)}`,
    "  is_default: true",
    "  checkpoints: checkpoints",
    "  vae: vae",
    "  controlnet: controlnet",
    "",
  ].join("\n");
  fs.writeFileSync(config, contents, { encoding: "utf8", mode: 0o600, flag: "wx" });
  return { configPath: config, modelRoot: realModelRoot };
};
