begin;
create table public.cloud_character_state_assignments(
 id uuid primary key default gen_random_uuid(),project_id uuid not null references public.cloud_projects(id) on delete cascade,owner_profile_id uuid not null references public.profiles(id) on delete cascade,
 character_profile_id uuid not null,character_version_id uuid not null references public.cloud_character_profile_versions(id) on delete cascade,
 start_page integer not null check(start_page>0),end_page integer not null check(end_page>=start_page),scene_key text not null default''check(char_length(scene_key)<=120),
 assignment_label text not null check(char_length(trim(assignment_label)) between 1 and 120),costume_override text not null default''check(char_length(costume_override)<=500),state_note text not null default''check(char_length(state_note)<=500),priority integer not null default 0 check(priority between 0 and 100),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 foreign key(character_profile_id,project_id)references public.cloud_character_profiles(id,project_id)on delete cascade
);
create index cloud_character_state_assignments_range_idx on public.cloud_character_state_assignments(character_version_id,start_page,end_page,priority desc);
alter table public.cloud_character_state_assignments enable row level security;grant select on public.cloud_character_state_assignments to authenticated;grant select,insert,update,delete on public.cloud_character_state_assignments to service_role;
create policy "cloud_character_state_assignments_owner_read" on public.cloud_character_state_assignments for select using(owner_profile_id=public.current_profile_id());
create or replace function public.save_cloud_character_state_assignment(p_project_id uuid,p_character_profile_id uuid,p_character_version_id uuid,p_start_page integer,p_end_page integer,p_scene_key text,p_assignment_label text,p_costume_override text,p_state_note text,p_priority integer default 0)returns uuid language plpgsql security definer set search_path=public,pg_temp as $$declare v_owner uuid:=public.current_profile_id();v_id uuid;begin
 if v_owner is null or p_start_page<1 or p_end_page<p_start_page or p_priority not between 0 and 100 or char_length(trim(coalesce(p_assignment_label,'')))not between 1 and 120 then raise exception 'cloud_character_state_assignment_invalid';end if;
 perform pg_advisory_xact_lock(hashtextextended(p_character_version_id::text,0));
 if not exists(select 1 from public.cloud_character_profile_versions v join public.cloud_character_profiles p on p.id=v.profile_id and p.project_id=v.project_id where v.id=p_character_version_id and v.profile_id=p_character_profile_id and v.project_id=p_project_id and v.owner_profile_id=v_owner and p.owner_profile_id=v_owner and p.deleted_at is null)or exists(select 1 from public.cloud_character_state_assignments a where a.character_version_id=p_character_version_id and int4range(a.start_page,a.end_page,'[]')&&int4range(p_start_page,p_end_page,'[]'))then raise exception 'cloud_character_state_assignment_invalid';end if;
 insert into public.cloud_character_state_assignments(project_id,owner_profile_id,character_profile_id,character_version_id,start_page,end_page,scene_key,assignment_label,costume_override,state_note,priority)values(p_project_id,v_owner,p_character_profile_id,p_character_version_id,p_start_page,p_end_page,trim(coalesce(p_scene_key,'')),trim(p_assignment_label),trim(coalesce(p_costume_override,'')),trim(coalesce(p_state_note,'')),p_priority)returning id into v_id;return v_id;end$$;
create or replace function public.delete_cloud_character_state_assignment(p_project_id uuid,p_assignment_id uuid)returns void language plpgsql security definer set search_path=public,pg_temp as $$begin delete from public.cloud_character_state_assignments where id=p_assignment_id and project_id=p_project_id and owner_profile_id=public.current_profile_id();if not found then raise exception 'cloud_character_state_assignment_not_found';end if;end$$;
revoke all on function public.save_cloud_character_state_assignment(uuid,uuid,uuid,integer,integer,text,text,text,text,integer),public.delete_cloud_character_state_assignment(uuid,uuid)from public,anon;
grant execute on function public.save_cloud_character_state_assignment(uuid,uuid,uuid,integer,integer,text,text,text,text,integer),public.delete_cloud_character_state_assignment(uuid,uuid)to authenticated,service_role;
notify pgrst,'reload schema';
commit;
