begin;
alter table public.cloud_projects add column if not exists production_context_revision bigint not null default 0 check(production_context_revision>=0);
alter table public.cloud_pages add column if not exists production_status text not null default 'not_started';
alter table public.cloud_pages add column if not exists production_status_updated_at timestamptz not null default now();
alter table public.cloud_pages add column if not exists production_status_updated_by_profile_id uuid references public.profiles(id) on delete set null;
alter table public.cloud_pages add column if not exists finalized_revision bigint check(finalized_revision>=0);
alter table public.cloud_pages add column if not exists reviewed_context_revision bigint check(reviewed_context_revision>=0);
alter table public.cloud_pages drop constraint if exists cloud_pages_production_status_check;
alter table public.cloud_pages add constraint cloud_pages_production_status_check check(production_status in('not_started','generating','review_required','revision_required','finalized'));
create index if not exists cloud_pages_production_status_idx on public.cloud_pages(project_id,production_status,page_number) where deleted_at is null;

create or replace function public.bump_cloud_production_context_revision() returns trigger language plpgsql security definer set search_path=public as $$
declare v_project_id uuid:=coalesce(new.project_id,old.project_id);begin update public.cloud_projects set production_context_revision=production_context_revision+1,updated_at=now() where id=v_project_id;return coalesce(new,old);end$$;
drop trigger if exists cloud_character_version_production_context on public.cloud_character_profile_versions;create trigger cloud_character_version_production_context after insert on public.cloud_character_profile_versions for each row execute function public.bump_cloud_production_context_revision();
drop trigger if exists cloud_style_version_production_context on public.cloud_style_bible_versions;create trigger cloud_style_version_production_context after insert on public.cloud_style_bible_versions for each row execute function public.bump_cloud_production_context_revision();
drop trigger if exists cloud_world_version_production_context on public.cloud_world_profile_versions;create trigger cloud_world_version_production_context after insert on public.cloud_world_profile_versions for each row execute function public.bump_cloud_production_context_revision();
drop trigger if exists cloud_visual_reference_production_context on public.cloud_visual_reference_assets;create trigger cloud_visual_reference_production_context after insert or delete on public.cloud_visual_reference_assets for each row execute function public.bump_cloud_production_context_revision();

create or replace function public.set_cloud_page_production_status(p_page_id uuid,p_status text) returns uuid language plpgsql security invoker set search_path=public as $$
declare v_page public.cloud_pages%rowtype;v_profile uuid:=public.current_profile_id();v_context bigint;v_project_revision bigint;begin
select * into v_page from public.cloud_pages where id=p_page_id and deleted_at is null for update;
if v_page.id is null or v_profile is null or not public.cloud_project_can_edit(v_page.project_id) or p_status not in('not_started','review_required','revision_required','finalized') then raise exception 'cloud_page_status_invalid';end if;
if p_status='finalized' and exists(select 1 from public.cloud_generation_jobs where page_id=p_page_id and status in('queued','running')) then raise exception 'cloud_page_finalize_active_jobs';end if;
select production_context_revision into v_context from public.cloud_projects where id=v_page.project_id;
update public.cloud_pages set production_status=p_status,production_status_updated_at=now(),production_status_updated_by_profile_id=v_profile,finalized_revision=case when p_status='finalized' then revision else null end,reviewed_context_revision=case when p_status='finalized' then v_context else reviewed_context_revision end where id=p_page_id;
update public.cloud_projects set revision=revision+1,updated_at=now() where id=v_page.project_id returning revision into v_project_revision;
insert into public.cloud_project_versions(project_id,revision,manifest,created_by_profile_id) values(v_page.project_id,v_project_revision,jsonb_build_object('event','page_production_status','pageId',p_page_id,'status',p_status),v_profile);return p_page_id;end$$;

create or replace function public.sync_cloud_page_production_status_from_job() returns trigger language plpgsql security definer set search_path=public as $$
declare v_status text;begin if new.page_id is null then return new;end if;select production_status into v_status from public.cloud_pages where id=new.page_id;if v_status='finalized' then raise exception 'cloud_page_finalized';end if;
if exists(select 1 from public.cloud_generation_jobs where page_id=new.page_id and status in('queued','running')) then v_status:='generating';elsif exists(select 1 from public.cloud_generation_jobs where page_id=new.page_id and status='failed') then v_status:='revision_required';elsif new.status='completed' then v_status:='review_required';else v_status:=coalesce(v_status,'not_started');end if;
update public.cloud_pages set production_status=v_status,production_status_updated_at=now() where id=new.page_id;return new;end$$;
drop trigger if exists cloud_generation_job_page_status on public.cloud_generation_jobs;create trigger cloud_generation_job_page_status after insert or update of status on public.cloud_generation_jobs for each row execute function public.sync_cloud_page_production_status_from_job();

create or replace function public.acquire_cloud_page_edit_lock(p_page_id uuid,p_lock_token uuid,p_lease_seconds integer default 120) returns timestamptz language plpgsql security definer set search_path=public as $$
declare v_page public.cloud_pages%rowtype;v_profile uuid:=public.current_profile_id();v_expires timestamptz;begin select * into v_page from public.cloud_pages where id=p_page_id and deleted_at is null;if v_page.id is null or v_profile is null or not public.cloud_project_can_edit(v_page.project_id) or p_lease_seconds not between 60 and 300 then raise exception 'cloud_page_lock_invalid';end if;if v_page.production_status='finalized' then raise exception 'cloud_page_finalized';end if;
insert into public.cloud_page_edit_locks(page_id,project_id,locked_by_profile_id,lock_token,lease_expires_at) values(v_page.id,v_page.project_id,v_profile,p_lock_token,now()+make_interval(secs=>p_lease_seconds)) on conflict(page_id) do update set locked_by_profile_id=excluded.locked_by_profile_id,lock_token=excluded.lock_token,lease_expires_at=excluded.lease_expires_at,updated_at=now() where public.cloud_page_edit_locks.lease_expires_at<=now() or(public.cloud_page_edit_locks.locked_by_profile_id=v_profile and public.cloud_page_edit_locks.lock_token=p_lock_token) returning lease_expires_at into v_expires;if v_expires is null then raise exception 'cloud_page_locked';end if;return v_expires;end$$;

create or replace function public.save_cloud_page_snapshot(p_page_id uuid,p_expected_revision bigint,p_canvas jsonb) returns table(page_id uuid,revision bigint,updated_at timestamptz) language plpgsql security invoker set search_path=public as $$
declare v_page public.cloud_pages%rowtype;v_profile_id uuid:=public.current_profile_id();v_project_revision bigint;v_now timestamptz:=clock_timestamp();begin if v_profile_id is null or jsonb_typeof(p_canvas)<>'object' or pg_column_size(p_canvas)>2097152 then raise exception 'invalid_snapshot_input';end if;select * into v_page from public.cloud_pages where id=p_page_id for update;if not found or not public.cloud_project_can_edit(v_page.project_id) then raise exception 'page_not_found';end if;if v_page.production_status='finalized' then raise exception 'cloud_page_finalized';end if;if v_page.revision<>p_expected_revision then raise exception 'revision_conflict:%',v_page.revision;end if;
update public.cloud_pages set revision=cloud_pages.revision+1,updated_at=v_now,production_status=case when production_status='not_started' then 'revision_required' else production_status end,production_status_updated_at=v_now where id=p_page_id returning cloud_pages.revision into revision;insert into public.cloud_canvas_snapshots(project_id,page_id,revision,canvas,created_by_profile_id,created_at) values(v_page.project_id,p_page_id,revision,p_canvas,v_profile_id,v_now);update public.cloud_projects set revision=cloud_projects.revision+1,updated_at=v_now where id=v_page.project_id returning cloud_projects.revision into v_project_revision;insert into public.cloud_project_versions(project_id,revision,manifest,created_by_profile_id,created_at) values(v_page.project_id,v_project_revision,jsonb_build_object('event','page_snapshot','pageId',p_page_id,'pageRevision',revision),v_profile_id,v_now);page_id:=p_page_id;updated_at:=v_now;return next;end$$;

revoke all on function public.set_cloud_page_production_status(uuid,text) from public,anon;grant execute on function public.set_cloud_page_production_status(uuid,text) to authenticated,service_role;
commit;
