begin;
create table public.cloud_panel_designs(id uuid primary key default gen_random_uuid(),project_id uuid not null references public.cloud_projects(id)on delete cascade,owner_profile_id uuid not null references public.profiles(id)on delete cascade,page_id uuid not null,panel_id uuid not null,revision bigint not null default 1 check(revision>0),design jsonb not null check(jsonb_typeof(design)='object'and design->>'schemaVersion'='1'and jsonb_typeof(design->'orderIndex')='number'and pg_column_size(design)<=65536),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),foreign key(page_id,project_id)references public.cloud_pages(id,project_id)on delete cascade,unique(project_id,page_id,panel_id));
create table public.cloud_panel_design_versions(id uuid primary key default gen_random_uuid(),panel_design_id uuid not null references public.cloud_panel_designs(id)on delete cascade,project_id uuid not null references public.cloud_projects(id)on delete cascade,owner_profile_id uuid not null references public.profiles(id)on delete cascade,page_id uuid not null,panel_id uuid not null,revision bigint not null check(revision>0),design jsonb not null,created_at timestamptz not null default now(),unique(panel_design_id,revision));
create index cloud_panel_designs_page_order_idx on public.cloud_panel_designs(project_id,page_id,((design->>'orderIndex')::integer));create index cloud_panel_design_versions_design_idx on public.cloud_panel_design_versions(panel_design_id,revision desc);
alter table public.cloud_panel_designs enable row level security;alter table public.cloud_panel_design_versions enable row level security;grant select on public.cloud_panel_designs,public.cloud_panel_design_versions to authenticated;grant select,insert,update,delete on public.cloud_panel_designs,public.cloud_panel_design_versions to service_role;create policy "cloud_panel_designs_owner_read" on public.cloud_panel_designs for select using(owner_profile_id=public.current_profile_id());create policy "cloud_panel_design_versions_owner_read" on public.cloud_panel_design_versions for select using(owner_profile_id=public.current_profile_id());
create or replace function public.save_cloud_panel_design(p_project_id uuid,p_page_id uuid,p_panel_id uuid,p_expected_revision bigint,p_design jsonb)returns table(panel_design_id uuid,revision bigint)language plpgsql security definer set search_path=public,pg_temp as $$declare v_owner uuid:=public.current_profile_id();v_existing public.cloud_panel_designs%rowtype;begin
 if v_owner is null or jsonb_typeof(p_design)<>'object'or p_design->>'schemaVersion'<>'1'or jsonb_typeof(p_design->'orderIndex')<>'number'or(p_design->>'orderIndex')::integer not between 0 and 499 or pg_column_size(p_design)>65536 or not exists(select 1 from public.cloud_projects where id=p_project_id and owner_profile_id=v_owner)or not exists(select 1 from public.cloud_pages p join public.cloud_canvas_snapshots s on s.project_id=p.project_id and s.page_id=p.id and s.revision=p.revision cross join lateral jsonb_array_elements(coalesce(s.canvas->'panels','[]'::jsonb)) panel where p.id=p_page_id and p.project_id=p_project_id and p.deleted_at is null and panel->>'id'=p_panel_id::text)then raise exception'cloud_panel_design_invalid';end if;
 select*into v_existing from public.cloud_panel_designs where project_id=p_project_id and page_id=p_page_id and panel_id=p_panel_id for update;
 if found then if p_expected_revision is distinct from v_existing.revision then raise exception'cloud_panel_design_revision_conflict';end if;update public.cloud_panel_designs set design=p_design,revision=cloud_panel_designs.revision+1,updated_at=now()where id=v_existing.id returning id,cloud_panel_designs.revision into panel_design_id,revision;
 else if p_expected_revision is not null then raise exception'cloud_panel_design_revision_conflict';end if;insert into public.cloud_panel_designs(project_id,owner_profile_id,page_id,panel_id,design)values(p_project_id,v_owner,p_page_id,p_panel_id,p_design)returning id,cloud_panel_designs.revision into panel_design_id,revision;end if;
 insert into public.cloud_panel_design_versions(panel_design_id,project_id,owner_profile_id,page_id,panel_id,revision,design)values(panel_design_id,p_project_id,v_owner,p_page_id,p_panel_id,revision,p_design);return next;end$$;
revoke all on function public.save_cloud_panel_design(uuid,uuid,uuid,bigint,jsonb)from public,anon;grant execute on function public.save_cloud_panel_design(uuid,uuid,uuid,bigint,jsonb)to authenticated,service_role;notify pgrst,'reload schema';
commit;
