begin;
create table public.cloud_panel_continuity_states(
 id uuid primary key default gen_random_uuid(),project_id uuid not null references public.cloud_projects(id)on delete cascade,owner_profile_id uuid not null references public.profiles(id)on delete cascade,page_id uuid not null,panel_id uuid not null,
 subject_kind text not null check(subject_kind in('character','location','prop')),subject_id uuid not null,time_of_day text not null default''check(char_length(time_of_day)<=80),weather text not null default''check(char_length(weather)<=80),state_note text not null default''check(char_length(state_note)<=500),holding_hand text not null default'unspecified'check(holding_hand in('unspecified','left','right','both','none')),screen_side text not null default'unspecified'check(screen_side in('unspecified','left','center','right')),gaze_direction text not null default''check(char_length(gaze_direction)<=120),continues_from_panel_id uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 foreign key(page_id,project_id)references public.cloud_pages(id,project_id)on delete cascade,unique(project_id,page_id,panel_id,subject_kind,subject_id)
);
create index cloud_panel_continuity_states_panel_idx on public.cloud_panel_continuity_states(project_id,page_id,panel_id);
alter table public.cloud_panel_continuity_states enable row level security;grant select on public.cloud_panel_continuity_states to authenticated;grant select,insert,update,delete on public.cloud_panel_continuity_states to service_role;create policy "cloud_panel_continuity_states_owner_read" on public.cloud_panel_continuity_states for select using(owner_profile_id=public.current_profile_id());
create or replace function public.save_cloud_panel_continuity_state(p_project_id uuid,p_page_id uuid,p_panel_id uuid,p_subject_kind text,p_subject_id uuid,p_time_of_day text,p_weather text,p_state_note text,p_holding_hand text,p_screen_side text,p_gaze_direction text,p_continues_from_panel_id uuid default null)returns uuid language plpgsql security definer set search_path=public,pg_temp as $$declare v_owner uuid:=public.current_profile_id();v_id uuid;begin
 if v_owner is null or p_subject_kind not in('character','location','prop')or p_holding_hand not in('unspecified','left','right','both','none')or p_screen_side not in('unspecified','left','center','right')or not exists(select 1 from public.cloud_pages p join public.cloud_canvas_snapshots s on s.project_id=p.project_id and s.page_id=p.id and s.revision=p.revision cross join lateral jsonb_array_elements(coalesce(s.canvas->'panels','[]'::jsonb)) panel where p.id=p_page_id and p.project_id=p_project_id and p.deleted_at is null and panel->>'id'=p_panel_id::text)or not public.cloud_visual_subject_exists(p_project_id,p_subject_kind,p_subject_id)or(p_continues_from_panel_id is not null and(p_continues_from_panel_id=p_panel_id or not exists(select 1 from public.cloud_pages p join public.cloud_canvas_snapshots s on s.project_id=p.project_id and s.page_id=p.id and s.revision=p.revision cross join lateral jsonb_array_elements(coalesce(s.canvas->'panels','[]'::jsonb)) panel where p.project_id=p_project_id and p.deleted_at is null and panel->>'id'=p_continues_from_panel_id::text)))then raise exception 'cloud_panel_continuity_state_invalid';end if;
 if not exists(select 1 from public.cloud_projects p where p.id=p_project_id and p.owner_profile_id=v_owner)then raise exception 'cloud_panel_continuity_state_invalid';end if;
 insert into public.cloud_panel_continuity_states(project_id,owner_profile_id,page_id,panel_id,subject_kind,subject_id,time_of_day,weather,state_note,holding_hand,screen_side,gaze_direction,continues_from_panel_id)values(p_project_id,v_owner,p_page_id,p_panel_id,p_subject_kind,p_subject_id,trim(coalesce(p_time_of_day,'')),trim(coalesce(p_weather,'')),trim(coalesce(p_state_note,'')),p_holding_hand,p_screen_side,trim(coalesce(p_gaze_direction,'')),p_continues_from_panel_id)on conflict(project_id,page_id,panel_id,subject_kind,subject_id)do update set time_of_day=excluded.time_of_day,weather=excluded.weather,state_note=excluded.state_note,holding_hand=excluded.holding_hand,screen_side=excluded.screen_side,gaze_direction=excluded.gaze_direction,continues_from_panel_id=excluded.continues_from_panel_id,updated_at=now()where cloud_panel_continuity_states.owner_profile_id=v_owner returning id into v_id;return v_id;end$$;
create or replace function public.delete_cloud_panel_continuity_state(p_project_id uuid,p_state_id uuid)returns void language plpgsql security definer set search_path=public,pg_temp as $$begin delete from public.cloud_panel_continuity_states where id=p_state_id and project_id=p_project_id and owner_profile_id=public.current_profile_id();if not found then raise exception 'cloud_panel_continuity_state_not_found';end if;end$$;
revoke all on function public.save_cloud_panel_continuity_state(uuid,uuid,uuid,text,uuid,text,text,text,text,text,text,uuid),public.delete_cloud_panel_continuity_state(uuid,uuid)from public,anon;grant execute on function public.save_cloud_panel_continuity_state(uuid,uuid,uuid,text,uuid,text,text,text,text,text,text,uuid),public.delete_cloud_panel_continuity_state(uuid,uuid)to authenticated,service_role;notify pgrst,'reload schema';
commit;
