export type Project = {
  id: string;
  title: string;
  subtitle: string;
  description: string;
  genre: string;
  ageRating: "全年齢" | "12歳以上" | "15歳以上" | "成人向け";
  readingDirection: "rtl" | "ltr";
  width: number;
  height: number;
  dpi: number;
  storagePath: string;
  coverAssetId: string | null;
  createdAt: string;
  updatedAt: string;
  lastOpenedAt: string | null;
};
export type Episode = {
  id: string;
  projectId: string;
  title: string;
  orderIndex: number;
  createdAt: string;
  updatedAt: string;
};
export type Page = {
  id: string;
  episodeId: string;
  pageNumber: number;
  orderIndex: number;
  width: number;
  height: number;
  backgroundColor: string;
  imageAssetId: string | null;
  prompt: string;
  negativePrompt: string;
  notes: string;
  createdAt: string;
  updatedAt: string;
};
export type Panel = {
  id: string;
  pageId: string;
  name: string;
  orderIndex: number;
  zIndex: number;
  x: number;
  y: number;
  width: number;
  height: number;
  rotation: number;
  visible: boolean;
  locked: boolean;
  borderColor: string;
  borderWidth: number;
  fillColor: string;
  imageAssetId: string | null;
  imageFit: "cover" | "contain" | "manual";
  imageOffsetX: number;
  imageOffsetY: number;
  imageScale: number;
  imageRotation: number;
  imageOpacity: number;
  prompt: string;
  negativePrompt: string;
  generationStatus: string;
  metadata: string;
  createdAt: string;
  updatedAt: string;
};
export type Balloon = {
  id: string;
  pageId: string;
  name: string;
  type: "speech_ellipse" | "speech_rounded" | "narration_box";
  x: number;
  y: number;
  width: number;
  height: number;
  rotation: number;
  zIndex: number;
  visible: boolean;
  locked: boolean;
  fillColor: string;
  strokeColor: string;
  strokeWidth: number;
  opacity: number;
  tailDirection: string;
  tailOffset: number;
  createdAt: string;
  updatedAt: string;
};
export type TextObject = {
  id: string;
  pageId: string;
  parentBalloonId: string | null;
  name: string;
  text: string;
  writingMode: "horizontal" | "vertical";
  x: number;
  y: number;
  width: number;
  height: number;
  rotation: number;
  zIndex: number;
  visible: boolean;
  locked: boolean;
  fontFamily: string;
  fontSize: number;
  fontWeight: number;
  color: string;
  textAlign: "start" | "center" | "end";
  verticalAlign: "top" | "middle" | "bottom";
  lineHeight: number;
  letterSpacing: number;
  padding: number;
  opacity: number;
  createdAt: string;
  updatedAt: string;
};
export type Asset = {
  id: string;
  projectId: string;
  fileName: string;
  relativePath: string;
  mimeType: string;
  width: number;
  height: number;
  byteSize: number;
  sha256: string;
  createdAt: string;
};
export type ProjectBundle = {
  project: Project;
  episodes: Episode[];
  pages: Page[];
  panels: Panel[];
  balloons: Balloon[];
  textObjects: TextObject[];
  assets: Asset[];
};

export function ordered<T extends { orderIndex: number }>(items: T[]) {
  return [...items].sort((a, b) => a.orderIndex - b.orderIndex);
}
export function nextOrderIndex<T extends { orderIndex: number }>(items: T[]) {
  return items.length ? Math.max(...items.map((x) => x.orderIndex)) + 1 : 0;
}
